INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (1, 'ALL PROJECT', 'ALL PROJECT', 1, 0, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (2, 'CAIRN', 'CAIRN', 0, 0, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (3, 'MV27', 'MV27', 0, 0, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (4, 'WARTSILA', 'WARTSILA', 1, 0, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (5, 'YINSON E-HOUSE', 'YINSON E-HOUSE', 1, 0, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (6, 'YINSON PGM', 'YINSON PGM', 1, 0, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (7, 'VWS ( MOHO )', 'VWS ( MOHO )', 0, 0, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (8, 'KAOMBO', 'KAOMBO', 1, 0, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (9, 'TEN E-HOUSE', 'TEN E-HOUSE', 0, 0, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (10, 'TEN MODULE', 'TEN MODULE', 0, 0, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (11, 'YINSON', 'YINSON', 1, 0, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (12, 'MOHO NORD', 'MOHO NORD', 0, 0, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (13, 'KAOMBO', 'KAOMBO', 0, 0, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (14, 'JANGKRIK', 'JANGKRIK', 1, 0, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (15, 'BIDDING', 'BIDDING', 1, 0, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (16, 'TRAINING', 'TRAINING', 1, 0, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (17, 'TCO', 'TCO', 1, 0, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (18, 'EH00009001', 'Schneider TCO 1 (4 units) - Common', 1, 1, 1, 1501995);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (19, 'EH00010001', 'Schneider TCO 1 (3 units) - Common', 1, 1, 1, 1501995);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (20, 'CM00007901', 'BW Offshore Stage 1 and 3,Suction Bottle', 0, 1, 1, 1501997);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (21, 'CM00002901', 'Wartsila-Kraken PwGen Mds (WEI 1403-167)', 1, 1, 1, 1501997);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (22, 'EH00007001', 'Kaombo E House (PT WEI 1410-172)', 1, 1, 1, 1501995);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (23, 'CM00005901', 'YinSon OCTP PowerGen (PT WEI 173)', 1, 1, 1, 1501997);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (24, 'CM00006001', 'Jangkrik Tertiary (PT WEI 175)', 1, 1, 1, 1501997);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (25, 'IDCO', 'PRODUCTION MANAGEMENT', 1, 1, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (26, 'IDCW', 'FITTER/WELDER', 1, 1, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (27, 'IDENGG', 'ENGINEERING', 1, 1, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (28, 'IDPMPP', 'PRODUCTION MANAGEMENT', 1, 1, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (29, 'IDQAQC', 'QA/QC', 1, 1, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (31, 'CP00013902', 'SHI offGas Recovery comp package G410', 1, 1, 1, 1501997);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (32, 'EH00011001', 'Schneider TCO Gathering (17 units)', 1, 1, 1, 1501997);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (33, 'EH00009002', 'Schneider TCO 1 (42SU3301)', 1, 1, 1, 1501995);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (34, 'EH00009003', 'Schneider TCO 1 (43SU3301)', 1, 1, 1, 1501995);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (35, 'EH00009004', 'Schneider TCO 1 (45SU3301)', 1, 1, 1, 1501995);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (36, 'EH00009005', 'Schneider TCO 1 (52SU3302)', 1, 1, 1, 1501995);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (37, 'EH00010002', 'Schneider TCO 2 (41SU3301)', 1, 1, 1, 1501995);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (38, 'EH00010003', 'Schneider TCO 2 (41SU3302)', 1, 1, 1, 1501995);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (39, 'EH00010004', 'Schneider TCO 2 (58SU3301)', 1, 1, 1, 1501995);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (40, 'IDRIGG', 'RIGGER', 1, 1, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (41, 'IDSCAF', 'SCAFFOLDER', 1, 1, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (42, 'IDPAINT', 'PAINTER', 1, 1, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (43, 'IDOPHELP', 'FORKLIFT /CNC OPERATOR & HELPER', 1, 1, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (44, 'IDPMP-NC', 'PROJECT MANAGEMENT (Non Core)', 1, 1, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (45, 'IDQC-NC', 'QC INSPECTOR (Non Core)', 1, 1, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (46, 'IDENG-NC', 'ENGINEER (Non Core)', 1, 1, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (47, 'IDCO-NC', 'PROJECT SUPPORT (Non Core)', 1, 1, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (48, 'EH00012001', 'Schneider BLNG', 0, 0, 1, 1501997);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (49, 'EH00012901', 'Schneider BLNG', 1, 1, 1, 1501997);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (50, 'CP00017901', 'Prosafe-Azurite Redeployment-Ruche-PTWEI', 1, 1, 1, 1400433);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (51, 'EH00013001', 'Siemens TCO Area HV SS', 1, 1, 1, 1700791);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (52, 'EH00011002', 'Schneider TCO Gathering FGP', 1, 1, 0, 1501997);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (53, 'OTV3002906', 'WEIL Services Project(PT WEI)', 1, 1, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (54, 'EH00011003', 'Schneider TCO Gathering (PSB)', 1, 1, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (55, 'SV00012001', 'TCO Gathering loadout (PT WEI)', 1, 1, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (56, 'CP00018901', 'PTSC -SVDN-CPP-M-0017-LP&MP Gas Comp_WEI', 0, 0, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (57, 'CP00018902', 'PTSC -SVDN LP & MP Gas Comp_WEI', 1, 1, 1, 1501997);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (58, 'CP00019901', 'PTSC CRD Gas Engine Generator(PTWEI)', 1, 1, 1, 1800415);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (59, 'CP00020901', 'CRD REINJECTION (PT WEI)', 1, 1, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (60, 'CP00021902', 'BGC - TEG PACKAGE (PT WEI)', 1, 1, 0, NULL);
INSERT INTO `tbl_project` (`project_id`, `project_uid`, `project`, `status_project`, `sap`, `approval_status`, `project_manager_id`) VALUES (61, 'SV00013901', 'Siemens UK Moray & Triton-Engg w(PTWEI)', 1, 1, 0, NULL);
